### ISSUE TITLE
Incorrect handler of Tuple types

### ISSUE THREAD

**Issue by sunoru** [lwabeke/Unmarshal.jl#21]
The `unmarshal` function for `Tuple` types cannot handle `Tuple` fields or `Tuple` of values in different types correctly. And the current implementation will unmarshal a tuple of several elements (e.g. in `Int` type) with a `Tuple{Int}` (actually, any `Tuple` types whose first type parameter is `Int`), which is inconsistent IMO because `Tuple{Int}` means the type of tuples that contain only one `Int`. Instead, it should be `NTuple{N, Int} where N`.
For example:
```julia
julia> import Unmarshal, JSON

julia> struct Foo
       x::Tuple
       end

julia> foo = Foo((1,5,6))
Foo((1, 5, 6))

julia> Unmarshal.unmarshal(Foo, JSON.parse(JSON.json(foo)))
ERROR: StackOverflowError:
Stacktrace:
 [1] unmarshal(::Type{Any}, ::Int64, ::Bool, ::Int64) at C:\Users\sunoru\pro\julia-packages\Unmarshal\src\Unmarshal.jl:147 (repeats 80000 times)

julia> t = (1,6,7)
(1, 6, 7)

julia> Unmarshal.unmarshal(Tuple{Int}, JSON.parse(JSON.json(t)))
(1, 6, 7)

julia> Unmarshal.unmarshal(typeof(t), JSON.parse(JSON.json(t)))
(1, 6, 7)

julia> t2 = (1, 3, 4.5)
(1, 3, 4.5)

julia> Unmarshal.unmarshal(typeof(t2), JSON.parse(JSON.json(t2)))
ERROR: InexactError: Int64(4.5)
Stacktrace:
 [1] Type at .\float.jl:703 [inlined]
 [2] unmarshal at C:\Users\sunoru\pro\julia-packages\Unmarshal\src\Unmarshal.jl:144 [inlined]
 [3] (::getfield(Unmarshal, Symbol("##5#6")){Tuple{Int64,Int64,Float64},Bool})(::Float64) at .\none:0
 [4] iterate(::Base.Generator{Array{Any,1},getfield(Unmarshal, Symbol("##5#6")){Tuple{Int64,Int64,Float64},Bool}}, ::Int64) at .\generator.jl:47
 [5] append_any(::Any, ::Vararg{Any,N} where N) at .\essentials.jl:680
 [6] unmarshal(::Type{Tuple{Int64,Int64,Float64}}, ::Array{Any,1}, ::Bool, ::Int64) at C:\Users\sunoru\pro\julia-packages\Unmarshal\src\Unmarshal.jl:117
 [7] unmarshal(::Type{Tuple{Int64,Int64,Float64}}, ::Array{Any,1}) at C:\Users\sunoru\pro\julia-packages\Unmarshal\src\Unmarshal.jl:112
 [8] top-level scope at none:0
```

I'm going to open a pull request to help fix this. Just want to file an issue first to let you know :)

**Comment by lwabeke** [comment]
Thanks, any help would be appreciated. 
I always suspected tuples were not properly handled and some of the newer named tuples, I have never looked into using and/or seeing what happens when trying to Unmarshal them.

**Comment by sunoru** [comment]
Do you think it's OK to add support for `unmarshal(::Type{T}, x) where T`?

Because it would be helpful when one wants to unmarshal a list into a `Vector{T} where T` or `Tuple{Vararg{T} where T}`, etc., which currently raises an error:
```julia
julia> Unmarshal.unmarshal(Vector, [1, 3])
ERROR: ArgumentError: no unmarshal function defined to convert Array{Int64,1} to Array{T,1} where T; consider providing a specialization
```

BTW, I also think the last three implementations are completely useless and wrong for there's no method for `Array(x::Number)`, and one cannot iterate over just a `Number`. Perhaps just delete them?

**Comment by sunoru** [comment]
And I found [this](https://github.com/lwabeke/Unmarshal.jl/blob/master/src/Unmarshal.jl#L26-L28) is useless since one won't want to unmarshal `String` into something like `Array{Int}`... It's also not covered in the tests.

**Comment by sunoru** [comment]
Thanks for merging the pr. Can you also create a new release for this package?

**Comment by lwabeke** [comment]
I tried to, but it didn't seem to work, I guess something changed in the release process. I will have to go follow up what is the current process.

**Comment by sunoru** [comment]
It can be very simple with this registrator :)

https://github.com/JuliaRegistries/Registrator.jl#install-registrator
