### ISSUE TITLE
Issue while unmarshalling a structure with a dictionary

### ISSUE THREAD

**Issue by GearsAD** [lwabeke/Unmarshal.jl#9]
Hi,

When I use the library to unmarshall structures that have dictionaries in them, an error occurs with message:
ArgumentError: Key ndel is missing from the structure Dict{String,String} and field is not Nullable
in unmarshal at Unmarshal/src/Unmarshal.jl:67
in unmarshal at Unmarshal/src/Unmarshal.jl:91
in unmarshal at Unmarshal/src/Unmarshal.jl:86

To reproduce:
mutable struct DictTest
    testDict::Dict{String, String}
end
dictTest = DictTest(Dict{String, String}("a" => "Test1", "b" => "Test2"))
Unmarshal.unmarshal(DictTest, JSON.parse(JSON.json(dictTest)))

Great library btw, thanks for writing!

**Comment by lwabeke** [comment]
Hi

I ran into this same issue last week. Have a fix, but don't have a good internet connection this will and will probably only be able to upload the patch next week.

**Comment by GearsAD** [comment]
Awesome, thank you! 👍

**Comment by lwabeke** [comment]
Should be resolved with version 0.1.0
